"""create projects and issues tables

Revision ID: 444623bedb31
Revises: 
Create Date: 2026-08-28 20:15:04.571780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '444623bedb31'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('backlog', 'in_progress', 'blocked', 'done', name='issue_status'), nullable=False),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', name='issue_priority'), nullable=False),
    sa.Column('assignee', sa.String(length=150), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_issues_priority'), 'issues', ['priority'], unique=False)
    op.create_index('ix_issues_project_id_status', 'issues', ['project_id', 'status'], unique=False)
    op.create_index(op.f('ix_issues_status'), 'issues', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_issues_status'), table_name='issues')
    op.drop_index('ix_issues_project_id_status', table_name='issues')
    op.drop_index(op.f('ix_issues_priority'), table_name='issues')
    op.drop_table('issues')
    op.drop_table('projects')
    # ### end Alembic commands ###

    # Manually added: PostgreSQL ENUM types are separate database objects
    # from the columns that use them, so dropping the 'issues' table does
    # NOT drop these types. Without this, a downgrade followed by a fresh
    # upgrade would fail with "type issue_status already exists".
    sa.Enum(name='issue_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='issue_priority').drop(op.get_bind(), checkfirst=True)
